service: lambda-get

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  apiHandler:
    handler: handler.api
    events:
      - http:
          path: people
          method: GET
          cors: true
      - http:
          path: people/{id}
          method: GET
          cors: true
      - http:
          path: planet
          method: GET
          cors: true
      - http:
          path: planet/{id}
          method: GET
          cors: true
      - http:
          path: vehicle
          method: GET
          cors: true
      - http:
          path: vehicle/{id}
          method: GET
          cors: true
      - http:
          path: specie
          method: GET
          cors: true
      - http:
          path: specie/{id}
          method: GET
          cors: true
